def config;
node(){
    configFileProvider([configFile(fileId: 'e739f5b7-27df-4f83-bd2a-7450d396412c', targetLocation: 'config')]) {
        config = readJSON file: 'config'
    }
}
pipeline {
           agent any
			options {
				skipDefaultCheckout(true)
			}
			tools{
				maven 'maven-default'
				dockerTool 'docker'
			}
            stages {
				stage('CleanWorkspace') {
                    steps {
						cleanWs()
                    }
                }
				stage('Checkout') {
                    steps {
						checkout scm
                    }
                }
                stage('UnitTest') {
                                     steps {
                 						script {
                 							if("${config.enviroment}"=='develop' && !readFile('pom.xml').contains('SNAPSHOT')){
                 								currentBuild.result = 'FAILURE'
                 								error("No se encontró una versión SNAPSHOT.")
                 							}
                 						}
                 						sh 'mvn clean install'
                                     }
                                 }
                stage('Scan') {
                					steps{
                						script {
                						  scannerHome = tool 'sonarQube'
                						}
                						withSonarQubeEnv('sonarQube') {
                						  sh "${scannerHome}/bin/sonar-scanner -Dproject.settings=cfg/sonar.properties"
                						}
                					}
                				}
        }
     }