def config;
node(){
 def fileId
    if ("${env.JOB_BASE_NAME}" == 'develop') {
        fileId = 'e739f5b7-27df-4f83-bd2a-7450d396412c'  // ID del archivo para la rama "develop"
    } else if ("${env.JOB_BASE_NAME}" == 'main') {
        fileId = '65047eb2-2a7d-4afc-bf15-4461e842c721'  // ID del archivo para la rama "main"
    }
    configFileProvider([configFile(fileId: fileId, targetLocation: 'config')]) {
        config = readJSON file: 'config'
    }
}
pipeline {
           agent any
			options {
				skipDefaultCheckout(true)
			}
			tools{
				maven 'maven-default'
				dockerTool 'docker'
			}
            stages {
				stage('CleanWorkspace') {
                    steps {
						cleanWs()
                    }
                }
				stage('Checkout') {
                    steps {
						checkout scm
                    }
                }
                stage('UnitTest') {
                                     steps {

                 		        sh 'mvn clean test jacoco:prepare-agent jacoco:report'

                                     }
                                     post{
                                        always{
                                            junit '**/target/surefire-reports/TEST-*.xml'
                                        }
                                     }
                                 }
                stage('Build') {
                    steps {
						sh 'mvn -f pom.xml clean install -DskipTests'
                    }
                         post{
                               failure{
                                 script {
                                   slackSend( channel: "despliegues",  message: "El proyecto ${ARTIFACT_ID} sufrió un error en el despliegue")
                                       }
                                     }
                              }
                }                
                stage('Scan and Analysis SAST') {
                					steps{
                						script {
                						  scannerHome = tool 'sonarQube'
                						}
                						withSonarQubeEnv('sonarQube') {
                						  sh "${scannerHome}/bin/sonar-scanner -Dproject.settings=cfg/sonar.properties"
                						}
                					}
                				}
                stage('Analysis DAST') {
                					steps{
                						dependencyCheck additionalArguments: '--format HTML' , odcInstallation:'DP-check'
                                        dependencyCheckPublisher pattern: '**/dependency-check-report.html'

                					}
                				}
        }
     }