apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-hispam-budget
  namespace: hispam
  labels:
    app: "ms-hispam-budget"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-hispam-budget
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ms-hispam-budget
    spec:
      containers:
        - name: ms-hispam-budget
          image: acrhispam.azurecr.io/ms-hispam-budget:0.4.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
           - name: ENV
             value: ambiente
           - name: SPRING_APPLICATION_JSON
             value: '{"spring":{"cloud":{"config":{"uri":"http://ms-hispam-config-server-svc.hispam.svc.cluster.local:4051","profile":"prod"}}}}'
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1500m
              memory: 3096Mi
      imagePullSecrets:
        - name: acr-hispam-registry
---
apiVersion: v1
kind: Service
metadata:
  name: ms-hispam-budget-svc
  namespace: hispam
  labels:
    app: "ms-hispam-budget"
spec:
  ports:
    - port: 4042
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: ms-hispam-budget

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-hispam-budget-ingress-nginx
  namespace: hispam
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/cors-allow-headers: "request-id, request-date, content-type"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, DELETE, PATCH, OPTIONS"
    cert-manager.io/cluster-issuer: letsencrypt-hispam
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Ingress: $ingress_name";
spec:
  rules:
    - host: aks-hispam-prd.eastus.cloudapp.azure.com
      http:
        paths:
          - backend:
              service:
                name: ms-hispam-budget-svc
                port:
                  number: 4042
            path: /jasper
            pathType: Prefix